- name: add case insensitive completion
  hosts: all
  become: true

  tasks:
    - name: add case insensitive completion
      ansible.builtin.lineinfile:
        path: /etc/inputrc
        line: set completion-ignore-case on
        create: true
        insertafter: EOF
        backup: true
