---
- hosts: all
  vars:
    git_user_name: "Vinícius Fontoura"
    git_user_email: "vinicius.fontoura@gmail.com"
  
  tasks:
    - name: change global user.name identification
      ansible.builtin.git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global

    - name: change global user.email identification
      ansible.builtin.git_config:
        name: user.email
        value: "{{ git_user_email }}"
        scope: global