- name: Config git
  vars:
    git_user_name: {{ core_git_user_name }}
    git_user_email: {{ core_git_user_email }}

  tasks:
    - name: change global user.name identification
      ansible.builtin.git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global

    - name: change global user.email identification
      ansible.builtin.git_config:
        name: user.email
        value: "{{ git_user_email }}"
        scope: global
