- hosts: all
  become: true
  vars:
    discord_deb_url: "https://discord.com/api/download?platform=linux&format=deb"
    discord_deb_file: "/tmp/discord.deb"

  tasks:
    - name: get discord deb package
      get_url:
        url: "{{ discord_deb_url }}"
        dest: "{{ discord_deb_file }}"
        mode: 0644 # rw-r--r--
        force: yes

    - name: install discord
      apt:
        deb: "{{ discord_deb_file }}"
        state: present
        update_cache: true