- name: Install Docker
  become: true

  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: "{{ core_docker_gpg_key }}"
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "{{ core_docker_repo }}"
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
