- name: install discord
  become: true

  tasks:
    - name: get discord deb package
      get_url:
        url: "{{ core_discord_deb_url }}"
        dest: "{{ core_discord_deb_file }}"
        mode: "0644" # rw-r--r--
        force: true

    - name: install discord
      apt:
        deb: "{{ core_discord_deb_file }}"
        state: present
        update_cache: true
